In [7]:
import sys
sys.path.append('C:\\Users\\monty.minh\\Documents\\Optimizer\\')

In [8]:
from model import *
from model.data import Data

Define a file path to the Excel input file


In [9]:
filepath = 'Template.xlsx'

In [11]:
from model import *
from model.data import *


def raw_inputs():
    """
    Method to pull data from input Excel files.

    Below only includes a shortlist of attributes used 
    and the sheet where the data comes from. For detailed
    documentation, see Attributes.txt

    Outputs to data.py
    ------------------
    Data.product_list: list
        - Pull from "Product List"

    Data.factory_list: list
        - Pull from "Factory List"

    Data.factory_names: dict
        - Pull from "Factory Per Product"

    Data.inbound_cost_per_product: dict
        - Pull from "Inbound Cost Per Product"

    Data.outbound_cost_per_product: dict
        - Pull from "Outbound Cost Per Product"

    Data.efficiency_per_product: dict
        - Pull from "Efficiency Per Product"

    Data.capacity_constraints: list
        - Pull from "Capacity Constraints"

    Data.supply_constraints: list
        - Pull from "Supply Constraints"

    Data.capacity_volume: numpy.ndarray
        - Pull from "Capacity Volume"

    Data.demand_volume: numpy.ndarray
        - Pull from "Demand Volume"


    """

    # Data.product_list
    Data.product_list = pd.read_excel(
        Data.filepath, sheet_name='Product List')['PRODUCT'].values.tolist()

    # Data.factory_list
    Data.factory_list = pd.read_excel(
        Data.filepath, sheet_name='Factory List')['FACTORY'].values.tolist()

    # Data.factory_name/s (df temporary stores the work sheet)
    df = pd.read_excel(Data.filepath,
                       sheet_name='Factory Per Product',
                       index_col='PRODUCT')

    Data.factory_names = {
        prod: df.columns[df.loc[prod]].tolist()
        for prod in Data.product_list
    }

    del df

    # Data.inbound_cost_per_product
    df = pd.read_excel(Data.filepath,
                       sheet_name='Inbound Cost Per Product',
                       index_col='PRODUCT')

    Data.inbound_cost_per_product = {
        prod: df.loc[prod][Data.factory_names[prod]].tolist()
        for prod in Data.product_list
    }

    del df

    # Data.outbound_cost_per_product
    df = pd.read_excel(Data.filepath,
                       sheet_name='Outbound Cost Per Product',
                       index_col='PRODUCT')

    Data.outbound_cost_per_product = {
        prod: np.array(df.loc[prod][Data.factory_names[prod]]).flatten('F')
        for prod in Data.product_list
    }

    del df

    # Data.efficiency_per_product
    df = pd.read_excel(Data.filepath,
                       sheet_name='Efficiency Per Product',
                       index_col='PRODUCT')

    Data.efficiency_per_product = {
        prod: df.loc[prod][Data.factory_names[prod]].tolist()
        for prod in Data.product_list
    }

    del df

    # Data.capacity_constraints # Constraints has to start index from 1
    df = pd.read_excel(Data.filepath,
                       sheet_name='Capacity Constraints',
                       index_col='CONSTRAINTS')

    Data.capacity_constraints = [
        df.columns[df.iloc[cons]].tolist() for cons in range(df.shape[0])
    ]

    del df

    # Data.supply_constraints # Constraints has to start index from 1
    df = pd.read_excel(Data.filepath,
                       sheet_name='Supply Constraints',
                       index_col='CONSTRAINTS')

    Data.supply_constraints = [
        df.columns[df.iloc[cons]].tolist() for cons in range(df.shape[0])
    ]

    del df

    # Data.capacity_volume
    Data.capacity_volume = pd.read_excel(
        Data.filepath, sheet_name='Capacity Volume',
        index_col='CONSTRAINTS').to_numpy().flatten()

    Data.capacity_volume = Data.capacity_volume[~np.isnan(Data.capacity_volume
                                                          )][:, np.newaxis]

    # Data.demand_volume
    Data.demand_volume = pd.read_excel(
        Data.filepath, sheet_name='Demand Volume').VOLUME.to_numpy()[:, np.newaxis]


def processed_inputs():
    """
    Data processed from Raw Inputs

    Outputs to data.py
    ------------------
    Data.factory_sizes: dict
        - Process from Data.factory_names

    Data.customer_sizes: dict
        - Process from ...

    Data.dimF: int
        - Process from Data.factory_sizes

    Data.dimC: int
        - Process from Data.customer_sizes

    Data.dimFC: int
        - Process from Data.factory_sizes x Data.customer_sizes

    """

    # Data.factory_sizes
    Data.factory_sizes = {
        prod: len(Data.factory_names[prod])
        for prod in Data.product_list
    }

    # Data.customer_sizes (Pending changes)
    # Might want to do Data.customer_list and Data.customer_names
    # as well, for the postprocessing

    Data.customer_sizes = {
        prod:
            len(Data.outbound_cost_per_product[prod]) // Data.factory_sizes[
                prod]
        for prod in Data.product_list
    }

    # Data.dimF
    Data.dimF = sum(Data.factory_sizes.values())

    # Data.dimC
    Data.dimC = sum(Data.customer_sizes.values())

    # Data.dimFC
    Data.dimFC = sum(
        np.array(list(Data.factory_sizes.values())) *
        np.array(list(Data.customer_sizes.values())))


def preprocess():

    """
    Method to call on the raw and processed inputs, then checks if the inputs
    are logical through a series of assert statement. After doing this,
    if we get an error in an assert statement, we know the values is wrong,
    else we know that the input is not the correct format.

    """

    # Retrieve the inputs
    raw_inputs()
    processed_inputs()

    # Assert logicality of inputs

In [15]:
from model.randinp import *

In [17]:
A = RandomInputs()

A.generate()

In [34]:
np.linalg.inv(np.array([[1, 1], [1, 0]]))

array([[ 0.,  1.],
       [ 1., -1.]])

In [26]:
a = np.array([[1, 1, 1], [1, 0, 0]])

In [29]:
from sympy import Matrix

In [30]:
Matrix(np.linalg.pinv(a))

Matrix([
[-5.55111512312578e-17,  1.0],
[                  0.5, -0.5],
[                  0.5, -0.5]])

In [31]:
np.linalg.rref

AttributeError: module 'numpy.linalg' has no attribute 'rref'

In [32]:
from scipy.linalg import lu

In [33]:
lu(a)

(array([[1., 0.],
        [0., 1.]]),
 array([[1., 0.],
        [1., 1.]]),
 array([[ 1.,  1.,  1.],
        [ 0., -1., -1.]]))